# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/122jggFQZ4vQek2YDNozw5ISfiaE9cVKZ
"""

def card_generator(li_values, length):
  "generate cards given a list of values and the length of tuple."

  from itertools import permutations
  cards = list(permutations(li_values, length))

  return cards

wcst_cards = card_generator([1,2,3,4], 3)

print(len(wcst_cards))
print(wcst_cards)